#!/usr/bin/env python3
"""Can AI Shop You? — agent-readiness scanner (v2, branded)
Free automated checks + Index + full-audit lead capture.
Usage:  .venv/bin/python app.py            -> web UI on http://localhost:8899
        .venv/bin/python app.py <domain>   -> CLI scan
"""
import json, re, sys
import requests
from flask import Flask, request, render_template_string

AUDIT_EMAIL = "mahmood@canaishopyou.com"   # <- where "request full audit" clicks land
UA = "AgentReadyScanner/2.0 (+https://canaishopyou.com)"
TIMEOUT = 12

import os, json as _json, datetime
DATA_FILE = os.environ.get("DATA_FILE", "/tmp/cani_data.json")
BASELINE_SCANS = 41  # brands + tests already run by founder pre-launch
def _load():
    try:
        return _json.load(open(DATA_FILE))
    except Exception:
        return {"scans": [], "leads": []}
def _save(d):
    try:
        _json.dump(d, open(DATA_FILE, "w"))
    except Exception:
        pass
def log_scan(domain, score, grade):
    d = _load()
    d["scans"].append({"domain": domain, "score": score, "grade": grade,
                       "ts": _utcnow()})
    _save(d)
def log_lead(domain, score, email=""):
    d = _load()
    d["leads"].append({"domain": domain, "score": score, "email": email, "ts": _utcnow()})
    _save(d)
def scan_count():
    return BASELINE_SCANS + len(_load().get("scans", []))
def recent_scans(n=5):
    return list(reversed(_load().get("scans", [])))[:n]
def _utcnow():
    # avoid Date.now-style; use time
    import time
    return int(time.time())

AI_BOTS = {
    "OAI-SearchBot":  ("ChatGPT search & shopping visibility", "FATAL — store is invisible in ChatGPT answers"),
    "ChatGPT-User":   ("live page fetches during ChatGPT sessions", "SEVERE — AI can't verify price/stock mid-conversation"),
    "PerplexityBot":  ("Perplexity search & shopping", "SEVERE — invisible on Perplexity"),
    "GPTBot":         ("OpenAI training crawler only", "OK to block — does NOT affect shopping visibility"),
    "Googlebot":      ("Google search + AI Mode grounding", "FATAL — invisible on Google surfaces"),
    "Bingbot":        ("Bing + Microsoft Copilot grounding", "SEVERE — weak/no Copilot presence"),
}

# NOTE: this Index is generated by scale_prospects.py (Check-0 + deterministic scan over
# prospects.csv) and copied from scanner/index_generated.py. To grow it: add brands to
# prospects.csv, run `python scale_prospects.py`, and paste the new blocks here.
INDEX_ED1 = [
    ("hexclad.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("materialkitchen.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("flybyjing.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("brightland.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("graza.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("misen.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("casper.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bearaby.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("avocadogreenmattress.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("greatjonesgoods.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("floydhome.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("coyuchi.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("buffy.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("marinelayer.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("allbirds.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("trueclassictees.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("koio.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("ritual.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("nisolo.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("livemomentous.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("magicspoon.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("thursdayboots.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("liquiddeath.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jenis.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("athleticbrewing.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("davidprotein.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jonesroadbeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("iliabeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("glossier.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("tower28beauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("meritbeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("versedskin.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("rarebeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cuyana.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("monos.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("paireyewear.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("awaytravel.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bollandbranch.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("chubbiesshorts.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cutsclothing.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("harrys.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("vuoriclothing.com", 92, "A", "Healthy — Platform catalog rail (Shopify)"),
    ("buckmason.com", 90, "A", "Healthy — Platform catalog rail (Shopify)"),
    ("nomadgoods.com", 87, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("atoms.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinklmnt.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("fromourplace.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("tuftandneedle.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("parachutehome.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("tenthousand.cc", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("fahertybrand.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("outdoorvoices.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("rothys.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinkolipop.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinkpoppi.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("transparentlabs.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("kosas.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("madeincookware.com", 77, "B", "Platform catalog rail (Shopify)"),
    ("huel.com", 77, "B", "Platform catalog rail (Shopify)"),
    ("bombas.com", 75, "B", "Platform catalog rail (Shopify)"),
    ("peakdesign.com", 73, "B", "robots.txt blocks AI bots"),
    ("burrow.com", 72, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("brooklinen.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("gymshark.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("aloyoga.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("dagnedover.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("nectarsleep.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("spotandtango.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("article.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("nutrafol.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("bellroy.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("purple.com", 57, "C", "no product structured data → hallucinated-price risk"),
    ("ridge.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("warbyparker.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("ruggable.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("westernrise.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("seed.com", 55, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("youthtothepeople.com", 55, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("drunkelephant.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("beis.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("carawayhome.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("saatva.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("helixsleep.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("bonobos.com", 40, "D", "Bot-wall (HTTP 420) — AI shoppers can't read the store"),
    ("mizzenandmain.com", 40, "D", "Bot-wall (HTTP 429) — AI shoppers can't read the store"),
    ("drinkag1.com", 40, "D", "Bot-wall (HTTP 429) — AI shoppers can't read the store"),
    ("rhone.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("legionathletics.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("omsom.com", 35, "D", "no product structured data → hallucinated-price risk"),
    ("thefarmersdog.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
]

# category -> [domains] (for the competitive comparison table on report pages)
CATEGORIES = {
    "Cookware": ["hexclad.com", "materialkitchen.com", "brightland.co", "graza.co", "misen.com", "greatjonesgoods.com", "fromourplace.com", "madeincookware.com", "carawayhome.com"],
    "Food & beverage": ["flybyjing.com", "magicspoon.com", "liquiddeath.com", "jenis.com", "athleticbrewing.com", "davidprotein.com", "drinkolipop.com", "drinkpoppi.com", "omsom.com"],
    "Mattresses": ["casper.com", "bearaby.com", "avocadogreenmattress.com", "tuftandneedle.com", "nectarsleep.com", "purple.com", "saatva.com", "helixsleep.com"],
    "Home & bedding": ["floydhome.com", "coyuchi.com", "buffy.co", "bollandbranch.com", "parachutehome.com", "burrow.com", "brooklinen.com", "article.com", "ruggable.com"],
    "Apparel & activewear": ["marinelayer.com", "trueclassictees.com", "chubbiesshorts.com", "cutsclothing.com", "vuoriclothing.com", "buckmason.com", "tenthousand.cc", "fahertybrand.com", "outdoorvoices.com", "bombas.com", "gymshark.com", "aloyoga.com", "westernrise.com", "bonobos.com", "mizzenandmain.com", "rhone.com"],
    "Footwear": ["allbirds.com", "koio.co", "nisolo.com", "thursdayboots.com", "atoms.com", "rothys.com"],
    "Supplements & wellness": ["ritual.com", "livemomentous.com", "drinklmnt.com", "transparentlabs.com", "huel.com", "nutrafol.com", "seed.com", "drinkag1.com", "legionathletics.com"],
    "Beauty & skincare": ["jonesroadbeauty.com", "iliabeauty.com", "glossier.com", "tower28beauty.com", "meritbeauty.com", "versedskin.com", "rarebeauty.com", "kosas.com", "youthtothepeople.com", "drunkelephant.com"],
    "Bags & accessories": ["cuyana.com", "monos.com", "awaytravel.com", "dagnedover.com", "bellroy.com", "ridge.com", "beis.com"],
    "Eyewear": ["paireyewear.com", "warbyparker.com"],
    "Grooming": ["harrys.com"],
    "Electronics & gear": ["nomadgoods.com", "peakdesign.com"],
    "Pet": ["spotandtango.com", "thefarmersdog.com"],
}
# Prefer the generated Index (scale_prospects.py → index_generated.py) when present;
# the inline list above is the fallback. This makes growing the Index a one-file upload.
try:
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    from index_generated import INDEX_ED1, CATEGORIES  # noqa: F811
except Exception:
    pass

_INDEX = {d: (s, g, note) for d, s, g, note in INDEX_ED1}
_RANK = {d: i for i, (d, *_) in enumerate(INDEX_ED1, 1)}

def category_of(domain):
    for cat, doms in CATEGORIES.items():
        if domain in doms:
            return cat, doms
    return None, []

def brand_report(domain):
    """Public teaser data for an Index brand. Whitelisted to INDEX only (no arbitrary scans)."""
    if domain not in _INDEX:
        return None
    score, grade, note = _INDEX[domain]
    cat, doms = category_of(domain)
    peers = sorted([(d, _INDEX[d][0], _INDEX[d][1]) for d in doms if d in _INDEX],
                   key=lambda x: -x[1]) if cat else []
    return {"domain": domain, "score": score, "grade": grade, "note": note,
            "rank": _RANK.get(domain), "total": len(INDEX_ED1),
            "category": cat, "peers": peers, "tested_date": "July 2026"}

def fetch(url):
    try:
        return requests.get(url, headers={"User-Agent": UA}, timeout=TIMEOUT, allow_redirects=True)
    except Exception:
        return None

def parse_robots(text):
    groups, current_agents, rules = [], [], []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line: continue
        m = re.match(r"(?i)^(user-agent|disallow|allow)\s*:\s*(.*)$", line)
        if not m: continue
        key, val = m.group(1).lower(), m.group(2).strip()
        if key == "user-agent":
            if rules:
                groups.append((current_agents, rules)); current_agents, rules = [], []
            current_agents.append(val)
        else:
            rules.append((key, val))
    if current_agents or rules:
        groups.append((current_agents, rules))
    def status_for(bot):
        bot_l = bot.lower(); best = None
        for agents, rls in groups:
            agents_l = [a.lower() for a in agents]
            if bot_l in agents_l: prio = 2
            elif "*" in agents_l: prio = 1
            else: continue
            if best is None or prio > best[0]:
                best = (prio, rls)
        if best is None: return "unlisted"
        return "blocked" if any(k == "disallow" and v == "/" for k, v in best[1]) else "allowed"
    return {bot: status_for(bot) for bot in AI_BOTS}

def scan(domain):
    domain = re.sub(r"^https?://", "", domain.strip().lower()).split("/")[0]
    base = f"https://{domain}"
    checks, score = [], 0

    r = fetch(f"{base}/robots.txt")
    if r is None or r.status_code >= 400:
        checks.append(("Robots.txt AI-bot access", "WARN", 20,
                       f"robots.txt not reachable (HTTP {r.status_code if r else 'error'}) — bots default to allowed, but verify manually."))
        score += 20
    else:
        bots = parse_robots(r.text)
        fatal = [b for b in ("OAI-SearchBot", "PerplexityBot", "Googlebot", "Bingbot", "ChatGPT-User") if bots.get(b) == "blocked"]
        gpt_note = " (GPTBot blocked — training only, no sales impact)" if bots.get("GPTBot") == "blocked" else ""
        if fatal:
            checks.append(("Robots.txt AI-bot access", "FAIL", 0,
                           "; ".join(f"{b} BLOCKED → {AI_BOTS[b][1]}" for b in fatal) + gpt_note))
        else:
            checks.append(("Robots.txt AI-bot access", "PASS", 40, "All shopping/search bots allowed" + gpt_note))
            score += 40

    home = fetch(base)
    cf = False
    if home is not None:
        h = {k.lower(): v for k, v in home.headers.items()}
        cf = "cf-ray" in h or "cloudflare" in h.get("server", "").lower()
    if cf:
        checks.append(("CDN silent-block risk (Cloudflare)", "WARN", 5,
                       "Behind Cloudflare — AI crawlers are blocked BY DEFAULT for new zones since Jul 2025. Owner must verify AI-crawler settings in dashboard. High-value finding."))
        score += 5
    else:
        checks.append(("CDN silent-block risk", "PASS", 10, "No Cloudflare AI-blocking signature detected."))
        score += 10

    l = fetch(f"{base}/llms.txt")
    if l is not None and l.status_code == 200 and len(l.text) > 20:
        checks.append(("llms.txt", "PASS", 5, "Present (low real-world impact today, signals AI-awareness)."))
        score += 5
    else:
        checks.append(("llms.txt", "INFO", 3, "Absent — like 97% of the web; cheap hedge to add, minimal impact."))
        score += 3

    is_shopify = home is not None and "cdn.shopify.com" in (home.text or "")
    pj = fetch(f"{base}/products.json?limit=5")
    pj_ok = False
    if pj is not None and pj.status_code == 200:
        try: pj_ok = len(pj.json().get("products", [])) > 0
        except Exception: pj_ok = False
    if is_shopify and pj_ok:
        checks.append(("Platform catalog rail (Shopify)", "PASS", 15,
                       "Shopify store with open product JSON — eligible for the Shopify Catalog rail into ChatGPT/Copilot/Google (on by default since Mar 2026). Verify merchant hasn't opted out."))
        score += 15
    elif is_shopify:
        checks.append(("Platform catalog rail (Shopify)", "WARN", 7,
                       "Shopify detected but products.json closed — catalog participation unclear; verify in admin."))
        score += 7
    else:
        checks.append(("Platform catalog rail", "INFO", 7,
                       "Not Shopify (or undetected) — no automatic catalog rail; feed rail (Google Merchant Center / OpenAI feed spec) matters more. Verify manually."))
        score += 7

    prod_url, jsonld_ok, offers_ok = None, False, False
    if pj_ok:
        try: prod_url = f"{base}/products/{pj.json()['products'][0]['handle']}"
        except Exception: prod_url = None
    if prod_url is None and home is not None:
        m = re.search(r'href="(/products/[^"?#]+)"', home.text or "")
        if m: prod_url = base + m.group(1)
    if prod_url:
        pr = fetch(prod_url)
        if pr is not None and pr.status_code == 200:
            for blob in re.findall(r'<script[^>]*application/ld\+json[^>]*>(.*?)</script>', pr.text, re.S | re.I):
                try: data = json.loads(blob.strip())
                except Exception: continue
                items = data if isinstance(data, list) else [data]
                for it in items:
                    graph = it.get("@graph", [it]) if isinstance(it, dict) else [it]
                    for node in graph:
                        if isinstance(node, dict) and "product" in str(node.get("@type", "")).lower():
                            jsonld_ok = True
                            if node.get("offers"): offers_ok = True
    if jsonld_ok and offers_ok:
        checks.append(("Product structured data (schema.org)", "PASS", 30,
                       f"Product JSON-LD with offers found on {prod_url} — AI can read name/price/availability reliably."))
        score += 30
    elif jsonld_ok:
        checks.append(("Product structured data", "WARN", 15,
                       f"Product JSON-LD found but no offers block on {prod_url} — price/stock may be misread → hallucinated-price risk."))
        score += 15
    else:
        checks.append(("Product structured data", "FAIL", 0,
                       f"No Product JSON-LD detected ({prod_url or 'no product page found'}) — AI must guess from raw HTML; wrong prices and missing listings likely."))

    grade = "A" if score >= 85 else "B" if score >= 70 else "C" if score >= 50 else "D" if score >= 35 else "F"
    return {"domain": domain, "score": score, "grade": grade, "checks": checks}

BASE_CSS = """
*{box-sizing:border-box;margin:0}
:root{--bg:#FAFAF8;--card:#FFFFFF;--ink:#18181B;--mut:#6B6B72;--dim:#9C9CA3;--hair:#ECEBE6;--line:#E4E3DD;
--accent:#0E9E70;--accent2:#0B7A55;
--gAb:#E7F7EF;--gAf:#0B7A4F;--gBb:#EFF6DE;--gBf:#4C7A0B;--gCb:#FDF1E0;--gCf:#B45309;--gDb:#FCEBE8;--gDf:#C13B2E;
--sh:0 1px 2px rgba(24,24,27,.05),0 8px 24px rgba(24,24,27,.05);--shlg:0 4px 14px rgba(24,24,27,.06),0 24px 60px rgba(24,24,27,.07)}
body{font-family:-apple-system,'SF Pro Display','Segoe UI',Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;-webkit-font-smoothing:antialiased;
background:radial-gradient(900px 420px at 50% -8%,#FFFFFF 0%,var(--bg) 70%)}
button,input,select,textarea{font-family:inherit}
.wrap{max-width:1000px;margin:0 auto;padding:0 24px 100px}
.nav{display:flex;justify-content:space-between;align-items:center;padding:22px 0;border-bottom:1px solid var(--hair)}
.nav .brand{font-size:1.22em;font-weight:800;color:var(--ink);text-decoration:none;letter-spacing:-.4px}
.nav .brand span{color:var(--accent)}
.nav .links a{margin-left:26px;font-weight:600;font-size:.95em;text-decoration:none;color:var(--mut)}
.nav .links a:hover{color:var(--ink)}
.hero{text-align:center;padding:76px 0 40px}
.hero h1{font-size:clamp(2.3em,5.2vw,3.85em);line-height:1.06;letter-spacing:-1.6px;font-weight:800;margin:0 auto 22px;max-width:880px}
.hero h1 em{font-style:normal;color:var(--accent)}
.hero p{color:var(--mut);font-size:1.16em;line-height:1.6;max-width:600px;margin:0 auto 34px;font-weight:450}
.statrow{display:flex;gap:14px;justify-content:center;margin:0 0 38px;flex-wrap:wrap}
.stat{background:var(--card);border:1px solid var(--hair);border-radius:14px;padding:18px 26px;text-align:center;box-shadow:var(--sh)}
.stat b{display:block;font-size:1.7em;font-weight:800;letter-spacing:-.6px;color:var(--ink)}
.stat span{color:var(--mut);font-size:.82em;font-weight:500}
form.scan{display:flex;gap:10px;max-width:580px;margin:0 auto}
input[name=domain],input[type=email]{flex:1;padding:15px 18px;font-size:1.05em;font-weight:500;border-radius:12px;border:1px solid #E1E0DA;background:var(--card);color:var(--ink);outline:none;transition:border .15s,box-shadow .15s}
input::placeholder{color:var(--dim)}
input[name=domain]:focus,input[type=email]:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(14,158,112,.14)}
button,.btn{padding:15px 26px;font-size:1em;font-weight:650;border-radius:12px;border:1px solid var(--ink);background:var(--ink);color:#fff;cursor:pointer;text-decoration:none;display:inline-block;box-shadow:var(--sh);transition:transform .12s,box-shadow .12s,background .12s}
button:hover,.btn:hover{transform:translateY(-1px);box-shadow:var(--shlg);background:#000}
.steps{display:flex;gap:18px;margin:52px 0 0;flex-wrap:wrap}
.step{flex:1;min-width:220px;background:var(--card);border:1px solid var(--hair);border-radius:16px;padding:28px;box-shadow:var(--sh)}
.step .n{font-size:.72em;color:var(--accent);font-weight:700;letter-spacing:.8px;text-transform:uppercase}
.step h4{margin:12px 0 8px;font-size:1.12em;font-weight:700}
.step p{color:var(--mut);font-size:.93em;line-height:1.6;font-weight:450}
.card{background:var(--card);border:1px solid var(--hair);border-radius:16px;padding:26px;margin:16px 0;box-shadow:var(--sh)}
.pill{display:inline-block;padding:4px 12px;border-radius:8px;font-weight:700;font-size:.8em;border:1px solid transparent;vertical-align:middle;letter-spacing:.2px}
.pA{background:var(--gAb);color:var(--gAf);border-color:#CDEBD9}.pB{background:var(--gBb);color:var(--gBf);border-color:#DCECBE}
.pC{background:var(--gCb);color:var(--gCf);border-color:#F6DDB8}.pD,.pF{background:var(--gDb);color:var(--gDf);border-color:#F5CFC9}
.PASS,.FAIL,.WARN,.INFO{display:inline-block;padding:3px 10px;border-radius:7px;font-size:.74em;font-weight:700;letter-spacing:.3px;border:1px solid transparent}
.PASS{background:var(--gAb);color:var(--gAf);border-color:#CDEBD9}.FAIL{background:var(--gDb);color:var(--gDf);border-color:#F5CFC9}
.WARN{background:var(--gCb);color:var(--gCf);border-color:#F6DDB8}.INFO{background:#F1F1EE;color:var(--mut);border-color:var(--hair)}
.score{font-size:3.6em;font-weight:800;letter-spacing:-2px;line-height:1}
.cA{color:var(--gAf)}.cB{color:var(--gBf)}.cC{color:var(--gCf)}.cD,.cF{color:var(--gDf)}
.gA{color:var(--gAf);font-weight:700}.gB{color:var(--gBf);font-weight:700}.gC{color:var(--gCf);font-weight:700}.gD,.gF{color:var(--gDf);font-weight:700}
.grade{font-size:1.05em;color:var(--mut);font-weight:600}
.dom{font-size:1.1em;font-weight:700}.outof{font-size:.42em;font-weight:700;color:var(--dim);letter-spacing:0}
.cta{background:linear-gradient(160deg,#232327,#161618);color:#fff;border:1px solid #26262B;border-radius:20px;text-align:center;padding:44px 32px;box-shadow:var(--shlg)}
.cta h3{margin:0 0 12px;font-size:1.55em;letter-spacing:-.6px;font-weight:800;color:#fff}
.cta p{color:#B6B6BC;margin:0 0 24px;line-height:1.6;font-weight:450}
.cta a.btn,.cta button{background:var(--accent);color:#fff;border-color:var(--accent);box-shadow:0 6px 20px rgba(14,158,112,.35)}
.cta a.btn:hover,.cta button:hover{background:var(--accent2);box-shadow:0 8px 26px rgba(14,158,112,.4)}
.cta input[type=email]{background:#fff;border-color:transparent}
.price{display:flex;gap:18px;justify-content:center;margin:30px 0 8px;flex-wrap:wrap}
.tier{background:var(--card);border:1px solid var(--hair);border-radius:16px;padding:26px;min-width:236px;text-align:left;box-shadow:var(--sh)}
.tier:nth-child(2){border:1.5px solid var(--accent);box-shadow:0 6px 24px rgba(14,158,112,.14)}
.tier b{font-size:1.7em;font-weight:800;letter-spacing:-.6px}.tier .per{color:var(--dim);font-size:.82em;font-weight:500}
.tier ul{margin:14px 0 0;padding-left:18px;color:var(--mut);font-size:.9em;line-height:1.85;font-weight:450}
table{width:100%;border-collapse:collapse}
td,th{padding:14px 10px;text-align:left}
th{color:var(--mut);font-weight:600;font-size:.76em;letter-spacing:.5px;text-transform:uppercase;border-bottom:1px solid var(--line)}
td{border-bottom:1px solid #F1F0EC}
td a{color:var(--ink);text-decoration:none;font-weight:600;border-bottom:1px solid transparent;transition:color .12s}
td a:hover{color:var(--accent);border-bottom-color:var(--accent)}
.repcard{background:var(--card);border:1px solid var(--hair);border-radius:22px;padding:46px 34px;text-align:center;margin:24px 0;box-shadow:var(--shlg)}
.repcard .score{font-size:clamp(3.4em,9vw,5em)}
.rank{color:var(--mut);font-size:1.05em;margin-top:14px;font-weight:500}
.yourrow{background:#F3FBF7!important}
.yourrow td{color:var(--ink)!important;font-weight:700}
.foot{text-align:center;color:var(--dim);margin-top:64px;font-size:.86em;line-height:1.9;font-weight:450}
.foot a{color:var(--mut);font-weight:600}
@media(max-width:640px){.hero h1{letter-spacing:-1px}form.scan{flex-direction:column}}
"""

NAV = """<div class="wrap"><div class="nav"><a class="brand" href="/">🔍 Can<span>AI</span>ShopYou</a>
<span class="links"><a href="/">Scanner</a><a href="/index-report">The Index</a><a href="/about">About</a><a href="mailto:mahmood@canaishopyou.com">Contact</a></span></div>"""

PAGE = """<!doctype html><html><head><title>Can AI Shop You? — Agent-Readiness Scanner & Index</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta property="og:title" content="Can AI Shop You?">
<meta property="og:description" content="Independent AI-commerce testing: can an AI shopping agent find, read and buy from your store? Run the free scan on your own store.">
<meta name="description" content="Independent AI-commerce testing: can an AI shopping agent actually find, read & buy from your store? Free scan + the Agent-Ready Index.">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🔍</text></svg>">
<style>""" + BASE_CSS + """</style></head><body>
""" + NAV + """
<div class="hero"><h1>AI shoppers are buying from stores right now.<br><em>Can they buy from yours?</em></h1>
<p>We send an autonomous AI shopping agent to actually find, read &amp; buy from your store — and show you, with recorded evidence, exactly where the journey breaks. Independent AI-commerce testing.</p>
<div class="statrow">
<div class="stat"><b>+1,200%</b><span>AI-referred retail traffic since '24 (Adobe)</span></div>
<div class="stat"><b>Reproduced</b><span>every finding, multiple runs</span></div>
<div class="stat"><b>Private</b><span>findings shared only with you</span></div>
</div>
<form class="scan" method="post"><input name="domain" placeholder="yourstore.com" value="{{domain or ''}}" required>
<button>Scan free</button></form></div>
{% if not r %}
<div class="steps">
<div class="step"><span class="n">STEP 1</span><h4>🔍 Scan the plumbing</h4><p>Crawler access, bot-walls, product data, catalog rails — the machine layer AI depends on. Free, 30 seconds.</p></div>
<div class="step"><span class="n">STEP 2</span><h4>🤖 Run the AI shopper</h4><p>The full audit sends an AI shopping agent to buy from your store and records every failure — blocked at the door, wrong variant, checkout breaks — reproduced across multiple runs.</p></div>
<div class="step"><span class="n">STEP 3</span><h4>📈 Fix what costs you</h4><p>Findings ranked by revenue impact, a 30-day roadmap, and a re-scan to prove the fix worked.</p></div>
</div>
<div class="price">
<div class="tier"><b>Free</b><div class="per">instant scan</div><ul><li>5 automated checks</li><li>Scored report card</li><li>No signup</li></ul></div>
<div class="tier"><b>$500</b><div class="per">full audit · 5 days</div><ul><li>AI shopper buy-test (recorded)</li><li>Reproduced evidence per failure</li><li>Fix roadmap + retest</li></ul></div>
<div class="tier"><b>$1,000<span class="per">/mo</span></b><div class="per">fix &amp; monitor</div><ul><li>Fix implementation</li><li>Weekly re-scans + alerts</li><li>Monthly report</li></ul></div>
</div>
<div class="card cta"><h3>Independent · reproduced · private</h3>
<p>We test how AI shopping systems handle your store, reproduce every finding across multiple runs, and share the detailed results privately with you — with the methodology. We don't publish scores or rankings.</p>
<a class="btn" href="/index-report">How it works →</a></div>
{% endif %}
{% if r %}
<div class="card" style="display:flex;align-items:center;gap:16px;flex-wrap:wrap"><span class="score c{{r.grade}}">{{r.score}}<span class="outof">/100</span></span> <span class="pill p{{r.grade}}" style="font-size:1em;padding:6px 16px">GRADE {{r.grade}}</span> <span class="dom">{{r.domain}}</span></div>
{% for name,status,pts,detail in r.checks %}<div class="card"><span class="{{status}}">{{status}}</span> &nbsp; <b>{{name}}</b> <span class="grade" style="font-size:.85em">({{pts}} pts)</span><br><span style="color:var(--mut)">{{detail}}</span></div>{% endfor %}
<div class="card cta"><h3>This was the free scan — the machine layer.</h3>
<p>The <b>full audit ($500)</b> sends an AI shopping agent to actually buy from your store, records every failure with reproduced evidence, and hands you the exact fixes —<br>then we retest to prove it's resolved. Delivered in 5 days.</p>
<form method="post" action="/request" style="display:flex;gap:10px;max-width:460px;margin:0 auto;flex-wrap:wrap;justify-content:center">
<input type="hidden" name="domain" value="{{r.domain}}"><input type="hidden" name="score" value="{{r.score}}">
<input name="email" type="email" placeholder="you@yourstore.com" required style="flex:1;min-width:220px">
<button>Request full audit →</button></form>
<p style="margin-top:12px;font-size:.85em;color:var(--dim)">or email <a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a></p></div>
{% endif %}
<div class="foot">CanAIShopYou · independent AI-commerce testing &amp; the Agent-Ready Index · Multan, Pakistan<br>
<a href="/about">About</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/index-report">The Index</a> · <a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a></div>
</div></body></html>"""

INDEX_PAGE = """<!doctype html><html><head><title>Independent AI-Commerce Testing | CanAIShopYou</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<meta property="og:title" content="Independent AI-Commerce Testing">
<meta property="og:description" content="We run controlled tests of whether AI shopping systems can find, read and buy from DTC stores. Findings are shared privately with each merchant.">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🔍</text></svg>">
<style>""" + BASE_CSS + """</style></head><body>
""" + NAV + """
<div class="hero"><h1>Independent <em>AI-commerce</em> testing</h1>
<p>We run controlled tests of whether AI shopping systems can discover, understand and buy from DTC stores.<br>
<b>Findings are shared privately with each merchant</b> — we don't publish scores, grades or rankings.</p></div>
<div class="card"><b>How it works</b><br><span style="color:var(--mut)">For each store we run realistic shopping scenarios and record where the journey succeeds or breaks — discovery, product information, selection and checkout. Every finding is reproduced and versioned, with documented limitations. Detailed observations go directly to the brand, with methodology available on request. We do not publish specific negative findings about any store.</span></div>
<div class="card cta"><h3>Want to know how AI shoppers do on your store?</h3>
<p>Run the free scan on your own store — or request a full independent test.</p>
<a class="btn" href="/">Scan your store free →</a></div>
<div class="foot">Independent AI-commerce testing · methodology available on request.<br>
<a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a></div>
</div></body></html>"""

FOOT = ('<div class="foot">CanAIShopYou · independent AI-commerce testing · Multan, Pakistan<br>'
        '<a href="/about">About</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · '
        '<a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a></div>')

def static_page(title, desc, hero_h1, hero_sub, body):
    """A plain, INDEXABLE trust page (About/Privacy/Terms) in the site's own design system.
    These are deliberately not noindex'd — they're the legitimacy signals search engines and AI
    assistants look for when someone checks whether the business is real."""
    head = ("<!doctype html><html><head><title>" + title + " | CanAIShopYou</title>"
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            '<meta name="description" content="' + desc + '">'
            '<meta property="og:title" content="' + title + ' | CanAIShopYou">'
            '<meta property="og:description" content="' + desc + '">'
            '<link rel="icon" href="data:image/svg+xml,<svg xmlns=\'http://www.w3.org/2000/svg\''
            " viewBox='0 0 100 100'><text y='.9em' font-size='90'>🔍</text></svg>\">"
            "<style>" + BASE_CSS + "</style></head><body>")
    hero = ('<div class="hero" style="padding-bottom:20px"><h1>' + hero_h1 + '</h1>'
            + ('<p>' + hero_sub + '</p>' if hero_sub else '') + '</div>')
    return head + NAV + hero + '<div class="wrap">' + body + FOOT + '</div></body></html>'

ABOUT_BODY = """
<div class="card"><b>What CanAIShopYou Is</b><br><span style="color:var(--mut)">
CanAIShopYou is an independent commerce intelligence platform. We benchmark how AI assistants and autonomous
shopping agents—the systems consumers use to research and buy—discover, evaluate, and recommend online brands.
Our infrastructure monitors where the discovery pipeline breaks, reproduces findings across multiple controlled
simulation runs, and provides documented, actionable intelligence privately to merchants.</span></div>

<div class="card"><b>Our Foundation</b><br><span style="color:var(--mut)">
CanAIShopYou operates as an independent commerce intelligence lab dedicated to building a transparent testing
layer for AI search. Headquartered in Multan, Pakistan, we analyze AI retrieval models to support
direct-to-consumer (DTC) brands across the US and EU. For methodologies or custom inquiries, reach our research
team directly at <a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a>.</span></div>

<div class="card"><b>How We Work</b><br><span style="color:var(--mut)">
We maintain absolute independence—we are not affiliated with, funded by, or endorsed by any brand we audit or
any AI provider. Every finding is rigorously reproduced and documented under specific environmental constraints
rather than broad generalizations. To protect brand integrity, we never publish negative findings publicly; all
vulnerability reports are routed directly and securely to the respective merchant.</span></div>

<div class="card"><b>Data &amp; Privacy Guardrails</b><br><span style="color:var(--mut)">
We operate on zero-trust data principles. We never request passwords, financial details, or credential
authorization. CanAIShopYou does not sell data, utilize advertising trackers, or store proprietary information.
Our automated scanner only parses publicly accessible pages of the storefronts submitted for analysis.</span></div>

<div class="card cta"><h3>Audit Your Brand's AI Visibility</h3>
<p>Run a free 30-second scan to evaluate your storefront, or contact us to schedule a comprehensive, full-scale
independent audit.</p>
<a class="btn" href="/">Run the free scan →</a></div>
"""

PRIVACY_BODY = """
<div class="card"><b>The short version</b><br><span style="color:var(--mut)">
We collect the minimum needed to run a test and send you the results. We don't sell your data, we don't share
it with advertisers, and we never ask for passwords, payment or wallet details.</span></div>

<div class="card"><b>What we collect</b><br><span style="color:var(--mut)">
• The store domain you submit to the scanner.<br>
• Your email address — only if you request a full audit or ask us to send findings.<br>
• Standard server logs (IP, timestamp) for security and reliability.</span></div>

<div class="card"><b>How we use it</b><br><span style="color:var(--mut)">
Only to run the requested test, deliver the results, and reply to you about them. We do not sell, rent or
trade your information, and we don't load third-party advertising trackers.</span></div>

<div class="card"><b>Access &amp; deletion</b><br><span style="color:var(--mut)">
Email <a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a> any time to see what we hold
about you, or to have it deleted.</span></div>
"""

TERMS_BODY = """
<div class="card"><b>What the service is</b><br><span style="color:var(--mut)">
CanAIShopYou provides independent tests of how AI shopping systems handle online stores. Findings are
<b>observations under stated conditions</b> — a specific AI model, on a specific date, in a specific test
environment — not guarantees of how every AI system or every shopper will behave.</span></div>

<div class="card"><b>No warranty</b><br><span style="color:var(--mut)">
The scanner and reports are provided "as is". AI systems change constantly, so findings can change too. We
don't warrant that results are complete or error-free, and business decisions you make from them are your own.</span></div>

<div class="card"><b>Acceptable use</b><br><span style="color:var(--mut)">
Use the scanner only on stores you own or are authorised to test. Don't use the service to attempt to harm,
overload or misrepresent any third party.</span></div>

<div class="card"><b>Independence</b><br><span style="color:var(--mut)">
CanAIShopYou is not affiliated with, sponsored by or endorsed by any brand we test, or by any AI provider
(including OpenAI, Google or Anthropic). All product and company names are the property of their owners.</span></div>

<div class="card"><b>Contact</b><br><span style="color:var(--mut)">
Questions about these terms? <a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a>.</span></div>
"""

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    r, domain = None, None
    if request.method == "POST":
        domain = request.form.get("domain", "")
        r = scan(domain)
        try: log_scan(r.get("domain",""), r.get("score",0), r.get("grade",""))
        except Exception: pass
        class O(dict): __getattr__ = dict.get
        r = O(r)
    return render_template_string(PAGE, r=r, domain=domain, scans=scan_count(), recent=recent_scans())

@app.route("/index-report")
def index_report():
    return render_template_string(INDEX_PAGE, rows=list(enumerate(INDEX_ED1, 1)), scans=scan_count())

@app.route("/about")
def about_page():
    return static_page("About", "Independent commerce intelligence for the age of AI search — how CanAIShopYou benchmarks AI discovery for DTC brands.",
                       "About <em>CanAIShopYou</em>", "Independent commerce intelligence for the age of AI search.", ABOUT_BODY)

@app.route("/privacy")
def privacy_page():
    return static_page("Privacy", "What data CanAIShopYou collects and how it's used. We don't sell data or ask for passwords or payment.",
                       "Privacy", "The minimum we need, used only to run your test.", PRIVACY_BODY)

@app.route("/terms")
def terms_page():
    return static_page("Terms", "Terms of use for CanAIShopYou — findings are observations under stated conditions, provided independently.",
                       "Terms", "Plain terms for an independent testing service.", TERMS_BODY)

@app.route("/report/<path:domain>")
def brand_report_page(domain):
    domain = re.sub(r"^https?://", "", domain.strip().lower()).split("/")[0].replace("www.", "")
    r = brand_report(domain)
    if not r:
        # not an Index brand — send them to the free scanner instead of scanning arbitrary input
        return render_template_string(BASE_DOC, body=(
            "<div class='wrap'><div class='card cta' style='margin-top:60px'>"
            "<h3>" + domain + " isn't on the Index yet</h3>"
            "<p>Run it through the free scanner to get its agent-readiness score.</p>"
            "<a class='btn' href='/'>Scan " + domain + " free →</a></div></div>")), 404
    class O(dict): __getattr__ = dict.get
    return render_template_string(REPORT_PAGE, r=O(r))


@app.route("/request", methods=["POST"])
def request_audit():
    domain = request.form.get("domain", "")
    email = request.form.get("email", "")
    score = request.form.get("score", "")
    try: log_lead(domain, score, email)
    except Exception: pass
    return render_template_string(BASE_DOC, body=(
        "<div class='wrap'><div class='card cta' style='margin-top:60px'>"
        "<h3>Request received ✓</h3><p>Your full audit of <b>" + (domain or "your store") +
        "</b> is queued. We\'ll email the 7-point report within 5 business days"
        + ((" to <b>"+email+"</b>") if email else "") + ".</p>"
        "<a class='btn' href='/'>← Back</a></div></div>"))

REPORT_PAGE = """<!doctype html><html><head><title>{{r.domain}} — Independent AI-Commerce Test | CanAIShopYou</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<meta name="description" content="{{r.domain}} was independently tested by CanAIShopYou for AI-commerce performance. Detailed findings are shared privately with the merchant.">
<meta property="og:title" content="{{r.domain}} — independently tested for AI commerce">
<meta property="og:description" content="CanAIShopYou independently tests whether AI shopping systems can find, read and buy from a store. Findings are shared privately with the merchant.">
<style>""" + BASE_CSS + """</style></head><body>""" + NAV + """
<div class="hero" style="padding-bottom:8px">
<h1><em>{{r.domain}}</em><br>independently tested</h1></div>
<div class="wrap">
<div class="repcard">
<div style="font-size:1.02em;color:var(--mut);font-weight:600">Last independently tested</div>
<div style="font-size:1.9em;font-weight:800;margin:6px 0;letter-spacing:-.5px">{{r.tested_date}}</div>
<div class="rank" style="margin-top:8px">Testing completed. Detailed findings are shared <b>privately with the merchant</b>.</div>
</div>
<div class="card"><b>What this is</b><br><span style="color:var(--mut)">CanAIShopYou runs independent, controlled tests of whether AI shopping systems can discover, understand and complete a purchase journey for a store. We do not publish specific findings — they go directly and privately to the brand. Methodology available on request.</span></div>

<div class="card cta" style="margin-top:30px">
<h3>On the {{r.domain}} team? Request your findings.</h3>
<p>We'll send the reproduced observations, the recorded evidence, and the methodology — free, no strings.</p>
<form class="scan" method="post" action="/request" style="max-width:520px">
<input type="hidden" name="domain" value="{{r.domain}}">
<input name="email" type="email" placeholder="you@{{r.domain}}" required>
<button type="submit">Send me the findings →</button></form>
</div>
<div class="foot">Independent AI-commerce testing · <a href="/">what we do</a> · <a href="/">scan your own store</a><br>
<a href="mailto:mahmood@canaishopyou.com">mahmood@canaishopyou.com</a></div>
</div></body></html>"""

BASE_DOC = """<!doctype html><html><head><title>CanAIShopYou</title>
<meta name="viewport" content="width=device-width,initial-scale=1"><style>""" + BASE_CSS + """</style></head><body>{{ body|safe }}</body></html>"""

if __name__ == "__main__":
    if len(sys.argv) > 1:
        res = scan(sys.argv[1])
        print(f"\n🔍 {res['domain']} — {res['score']}/100 (grade {res['grade']})")
        for name, status, pts, detail in res["checks"]:
            print(f"  [{status:4}] {name} ({pts}pts)\n         {detail}")
    else:
        app.run(port=8899)
