INDEX_ED1 = [
    ("hexclad.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("brightland.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("casper.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("flybyjing.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("graza.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("materialkitchen.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("misen.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bearaby.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("avocadogreenmattress.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("greatjonesgoods.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("coyuchi.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("buffy.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("floydhome.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("marinelayer.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("trueclassictees.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("allbirds.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("ritual.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("koio.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("nisolo.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("livemomentous.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("thursdayboots.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("magicspoon.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("liquiddeath.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("davidprotein.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jenis.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("athleticbrewing.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jonesroadbeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("glossier.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("versedskin.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("tower28beauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("iliabeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("monos.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("rarebeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("meritbeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cuyana.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("awaytravel.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("paireyewear.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("rowingblazers.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("knix.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("wearpepper.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("saturdaysnyc.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("halfdays.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("littlesleepies.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("blume.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("glamnetic.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("saltandstone.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("primallypure.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("rhodeskin.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("olly.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("buypeakperformance.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("1stphorm.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cleansimpleeats.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("shopbeam.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("88acres.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jojoschocolate.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("grove.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("foursigmatic.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("karmanuts.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("boxedwaterisbetter.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jonessoda.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("risebrewingco.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("slatemilk.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("popandbottle.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("minglemocktails.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("rookcoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("jot.co", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("artoftea.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("darkmattercoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("paradiseroasters.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("deathwishcoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("sfbaycoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("ptscoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("redbaycoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("tayst.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("coffeeam.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("wanderingbearcoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("stumptowncoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("lifeboostcoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("firebellytea.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("vervecoffee.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cocokind.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("terrakaffe.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("colourpop.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("juviasplace.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("ellamila.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bambuearth.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("credobeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("billyjealousy.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bodyhealth.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bareperformancenutrition.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("coppercompression.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("fentybeauty.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bioclarity.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("evlnutrition.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("shamelesspets.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("310nutrition.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("nativepet.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("campusprotein.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("sassywoof.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("petkrewe.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("feedpetaluma.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("portlandpetfoodcompany.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("halopets.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("chippinpet.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("luluandgeorgia.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("originalgrain.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("shinola.com", 95, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("bollandbranch.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("chubbiesshorts.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("cutsclothing.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("harrys.com", 93, "A", "Healthy — verify Cloudflare isn't blocking AI crawlers"),
    ("vuoriclothing.com", 92, "A", "Healthy — Platform catalog rail (Shopify)"),
    ("buckmason.com", 90, "A", "Healthy — Platform catalog rail (Shopify)"),
    ("nomadgoods.com", 87, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("dossier.co", 87, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinklmnt.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("atoms.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("thereformation.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("chamberlaincoffee.com", 85, "A", "verify Cloudflare isn't blocking AI crawlers"),
    ("fromourplace.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("tuftandneedle.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("parachutehome.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("tenthousand.cc", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("fahertybrand.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("outdoorvoices.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("rothys.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("transparentlabs.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinkolipop.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("drinkpoppi.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("kosas.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("everlane.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("thisisneeded.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("moonjuice.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("portrait.coffee", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("stashtea.com", 80, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("madeincookware.com", 77, "B", "Platform catalog rail (Shopify)"),
    ("huel.com", 77, "B", "Platform catalog rail (Shopify)"),
    ("bombas.com", 75, "B", "Platform catalog rail (Shopify)"),
    ("peakdesign.com", 73, "B", "robots.txt blocks AI bots"),
    ("burrow.com", 72, "B", "verify Cloudflare isn't blocking AI crawlers"),
    ("briogeohair.com", 70, "B", "robots.txt blocks AI bots"),
    ("brooklinen.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("aloyoga.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("gymshark.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("dagnedover.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("boyish.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("tenlittle.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("functionofbeauty.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("beautyofjoseon.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("ketone.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("bokksu.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("katzglutenfree.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("dvashorganics.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("gainful.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("skoutorganic.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("pitayafoods.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("mushroomjerky.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("betterbooch.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("juneshine.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("reborncoffee.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("tiestatea.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("goldenmoontea.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("onyxcoffeelab.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("madebynacho.com", 65, "C", "no product structured data → hallucinated-price risk"),
    ("thuma.co", 63, "C", "no product structured data → hallucinated-price risk"),
    ("nectarsleep.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("spotandtango.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("prose.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("thecitizenry.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("smalls.com", 62, "C", "no product structured data → hallucinated-price risk"),
    ("article.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("nutrafol.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("bellroy.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("typology.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("ollie.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("catperson.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("quince.com", 60, "C", "no product structured data → hallucinated-price risk"),
    ("purple.com", 57, "C", "no product structured data → hallucinated-price risk"),
    ("ridge.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("warbyparker.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("phlur.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("personanutrition.com", 57, "C", "no product structured data → hallucinated-price risk"),
    ("clevrblends.com", 57, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("alimapure.com", 57, "C", "no product structured data → hallucinated-price risk"),
    ("manlybands.com", 57, "C", "no product structured data → hallucinated-price risk"),
    ("ruggable.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("westernrise.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("seed.com", 55, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("youthtothepeople.com", 55, "C", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("drunkelephant.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("beis.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("curology.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("trinnylondon.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("biossance.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("humnutrition.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("drinkaguabonita.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("annmariegianni.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("nomnomnow.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("mejuri.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("thepearlsource.com", 55, "C", "no product structured data → hallucinated-price risk"),
    ("carawayhome.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("saatva.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("helixsleep.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("bonobos.com", 40, "D", "Bot-wall (HTTP 420) — AI shoppers can't read the store"),
    ("mizzenandmain.com", 40, "D", "Bot-wall (HTTP 429) — AI shoppers can't read the store"),
    ("drinkag1.com", 40, "D", "Bot-wall (HTTP 429) — AI shoppers can't read the store"),
    ("serenaandlily.com", 40, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("rhone.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("legionathletics.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("omsom.com", 35, "D", "no product structured data → hallucinated-price risk"),
    ("thefarmersdog.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("maelyscosmetics.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("spoiledchild.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
    ("truvani.com", 35, "D", "no product structured data → hallucinated-price risk"),
    ("petplate.com", 35, "D", "Bot-wall (HTTP 403) — AI shoppers can't read the store"),
]

CATEGORIES = {
    "Cookware": ["hexclad.com", "brightland.co", "graza.co", "materialkitchen.com", "misen.com", "greatjonesgoods.com", "fromourplace.com", "madeincookware.com", "carawayhome.com"],
    "Mattresses": ["casper.com", "bearaby.com", "avocadogreenmattress.com", "tuftandneedle.com", "nectarsleep.com", "purple.com", "saatva.com", "helixsleep.com"],
    "Food & beverage": ["flybyjing.com", "magicspoon.com", "liquiddeath.com", "davidprotein.com", "jenis.com", "athleticbrewing.com", "88acres.com", "jojoschocolate.com", "karmanuts.com", "boxedwaterisbetter.com", "jonessoda.com", "risebrewingco.com", "slatemilk.com", "popandbottle.com", "minglemocktails.com", "drinkolipop.com", "drinkpoppi.com", "bokksu.com", "katzglutenfree.com", "dvashorganics.com", "skoutorganic.com", "pitayafoods.com", "mushroomjerky.com", "betterbooch.com", "juneshine.com", "drinkaguabonita.com", "omsom.com"],
    "Home & bedding": ["coyuchi.com", "buffy.co", "floydhome.com", "grove.co", "luluandgeorgia.com", "bollandbranch.com", "parachutehome.com", "burrow.com", "brooklinen.com", "thuma.co", "thecitizenry.com", "article.com", "quince.com", "ruggable.com", "serenaandlily.com"],
    "Apparel & activewear": ["marinelayer.com", "trueclassictees.com", "rowingblazers.com", "knix.com", "wearpepper.com", "saturdaysnyc.com", "halfdays.com", "littlesleepies.com", "chubbiesshorts.com", "cutsclothing.com", "vuoriclothing.com", "buckmason.com", "thereformation.com", "tenthousand.cc", "fahertybrand.com", "outdoorvoices.com", "everlane.com", "bombas.com", "aloyoga.com", "gymshark.com", "boyish.com", "westernrise.com", "bonobos.com", "mizzenandmain.com", "rhone.com"],
    "Footwear": ["allbirds.com", "koio.co", "nisolo.com", "thursdayboots.com", "atoms.com", "rothys.com", "tenlittle.com"],
    "Supplements & wellness": ["ritual.com", "livemomentous.com", "olly.com", "buypeakperformance.com", "1stphorm.com", "cleansimpleeats.com", "shopbeam.com", "foursigmatic.com", "bodyhealth.com", "bareperformancenutrition.com", "coppercompression.com", "bioclarity.com", "evlnutrition.com", "310nutrition.com", "campusprotein.com", "drinklmnt.com", "transparentlabs.com", "thisisneeded.com", "moonjuice.com", "huel.com", "ketone.com", "gainful.com", "nutrafol.com", "personanutrition.com", "seed.com", "humnutrition.com", "drinkag1.com", "legionathletics.com", "truvani.com"],
    "Beauty & skincare": ["jonesroadbeauty.com", "glossier.com", "versedskin.com", "tower28beauty.com", "iliabeauty.com", "rarebeauty.com", "meritbeauty.com", "blume.com", "glamnetic.com", "saltandstone.com", "primallypure.com", "rhodeskin.com", "cocokind.com", "colourpop.com", "juviasplace.com", "ellamila.com", "bambuearth.com", "credobeauty.com", "billyjealousy.com", "fentybeauty.com", "dossier.co", "kosas.com", "briogeohair.com", "functionofbeauty.com", "beautyofjoseon.com", "prose.com", "typology.com", "phlur.com", "alimapure.com", "youthtothepeople.com", "drunkelephant.com", "curology.com", "trinnylondon.com", "biossance.com", "annmariegianni.com", "maelyscosmetics.com", "spoiledchild.com"],
    "Bags & accessories": ["monos.com", "cuyana.com", "awaytravel.com", "originalgrain.com", "shinola.com", "dagnedover.com", "bellroy.com", "ridge.com", "manlybands.com", "beis.com", "mejuri.com", "thepearlsource.com"],
    "Eyewear": ["paireyewear.com", "warbyparker.com"],
    "Coffee": ["rookcoffee.com", "jot.co", "artoftea.com", "darkmattercoffee.com", "paradiseroasters.com", "deathwishcoffee.com", "sfbaycoffee.com", "ptscoffee.com", "redbaycoffee.com", "tayst.com", "coffeeam.com", "wanderingbearcoffee.com", "stumptowncoffee.com", "lifeboostcoffee.com", "firebellytea.com", "vervecoffee.com", "terrakaffe.com", "chamberlaincoffee.com", "portrait.coffee", "stashtea.com", "reborncoffee.com", "tiestatea.com", "goldenmoontea.com", "onyxcoffeelab.com", "clevrblends.com"],
    "Pet": ["shamelesspets.com", "nativepet.com", "sassywoof.com", "petkrewe.com", "feedpetaluma.com", "portlandpetfoodcompany.com", "halopets.com", "chippinpet.com", "madebynacho.com", "spotandtango.com", "smalls.com", "ollie.com", "catperson.com", "nomnomnow.com", "thefarmersdog.com", "petplate.com"],
    "Grooming": ["harrys.com"],
    "Electronics & gear": ["nomadgoods.com", "peakdesign.com"],
}
